server:
  port: 8090
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      #ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/db1?currentSchema=grabbing
    username: u2
    password: p2
    driverClassName: org.postgresql.Driver