server:
  port: 8090
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres_u2_db1
    username: u2
    password: p2
    driverClassName: org.postgresql.Driver